-- liquibase formatted sql

-- changeSet User:1
create table person(
    id       int generated by default as identity primary key,
    email    varchar(100) unique,
    password varchar(100),
    role     varchar,
    name     varchar(120)
);
-- rollback drop table person;