-- liquibase formatted sql

-- changeSet User:1
create table user_(
    id       int generated by default as identity primary key,
    email    varchar(100) unique,
    password varchar(100),
    role     varchar
);
-- rollback drop table user;