-- liquibase formatted sql

-- changeSet User:3
create table favorites(
    id int generated by default as identity,
    person_id int references person (id),
    article_id int references article (id),
    primary key (person_id, article_id)
);
-- rollback drop table favorites;